# Generated by Django 5.1.7 on 2025-03-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_pessoas_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome',
            new_name='name',
        ),
    ]
