# Generated by Django 5.1.7 on 2025-03-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nome_pessoa_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='name',
            new_name='nome',
        ),
    ]
