# Generated by Django 5.1.7 on 2025-03-18 23:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pessoa_dt_criacao_alter_pessoa_dt_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='dt_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
