# Generated by Django 5.1.7 on 2025-03-19 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pessoa_dt_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='dt_nascimento',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
