# Generated by Django 5.1.7 on 2025-03-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pessoa_dt_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='dt_nascimento',
            field=models.DateField(),
        ),
    ]
